sudo: false
language: c
env:
  matrix:
  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
before_script:
- "./scripts/run-dynamodb-local.sh &"
script: stack $ARGS --no-terminal --install-ghc test --pedantic
deploy:
  provider: releases
  api_key:
    secure: Wk2Z/jislfOnyJg9BlFtJCX2CDgjiTM2XtU9EcFCksEtXhVtYAY/IaQYXuyusRm/cXOE3x3FQQvcWH2uazQCpZAfWFETEA88g+CRT/N3H0YJcL7ciQdN6huAuqxOT/XA5Wkmj1kspNM2mknE1alzRysyrkfmnkP4j3JcC2cDE9g=
  file: ".stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/web/web"
  on:
    tags: true
    repo: adbrowne/dynamodb-eventstore
cache:
  directories:
  - "$HOME/.stack"
