flags: {}
packages:
 - 'dynamodb-eventstore'
 - 'dynamodb-eventstore-web'
 - 'dynamodb-eventstore-client'
 - location:
    git: https://github.com/adbrowne/dodgerblue.git
    commit: d0c5c508c19f93aeb55d349fec0b37adbf8f07e9
resolver: lts-7
extra-deps:
 - aeson-diff-1.0.0.0
