flags: {}
packages:
 - 'dynamodb-eventstore'
 - 'dynamodb-eventstore-web'
 - 'dynamodb-eventstore-client'
 - location:
    git: https://github.com/adbrowne/dodgerblue.git
    commit: a42db6d59f385bba0a4ae5dbf60b8aa1f4a9d6b4
resolver: lts-7.0
extra-deps:
 - aeson-diff-1.1.0.0
 - edit-distance-vector-1.0.0.4
