flags: {}
packages:
 - '.'
 - location:
    git: https://github.com/adbrowne/dodgerblue.git
    commit: 318ff1e0ef3d4ea4d0123401a918f8008cdf6e8b
resolver: lts-6.14
extra-deps:
 - aeson-diff-1.0.0.0
 - haskell-src-exts-1.18.2
