flags: {}
packages:
- '.'
- location: 
    git: https://github.com/adbrowne/amazonka.git
    commit: 717610206e0b9e97d370e8099a2ce2f9d6137860
  extra-dep: true
  subdirs:
  - core
  - amazonka
  - amazonka-dynamodb
resolver: lts-3.1
